In [15]:
import numpy
numpy.version.version
arr=numpy.arange(0,100+1)
print(arr)
print("---------------------------------------------------------")
arr1 = [num for num in arr if num % 2 == 0]
print(arr1)
print("---------------------------------------------------------")
arr2 = [num for num in arr if num % 5 == 0]
print(arr2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
---------------------------------------------------------
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
---------------------------------------------------------
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [16]:
import numpy as np
np.array([0])
print("---------------------------------------------------------")
arr2 =np.arange(51,69)
print(arr2)
print("---------------------------------------------------------")
arr3=arr2.reshape((3,6))
print(arr3)
print("---------------------------------------------------------")
arr4 = arr3.reshape((6,3))
print(arr4)
print("---------------------------------------------------------")

---------------------------------------------------------
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68]
---------------------------------------------------------
[[51 52 53 54 55 56]
 [57 58 59 60 61 62]
 [63 64 65 66 67 68]]
---------------------------------------------------------
[[51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]]
---------------------------------------------------------


In [17]:
import pandas as pd
import numpy as np

data = pd.date_range(start='06/04/2019', end='08/21/2019')
datasave = []
for i in range(1, len(data)):
    if data[i].weekday() == 2:
        print(data[i].weekday())
        datasave.append(data[i])
ans = datasave
wed = np.array(ans)
wed = wed.reshape(3,4)
print(wed)
wed2 = [wed.T[i] for i in range (len(wed.T)) if i %2 !=0]
print(wed2)
wed3 = []
wed3.append(wed[0][1])
wed3.append(wed[0][3])
print(wed3)
wed4 = []
for i in range(0,len(wed)):
    wed4.append(wed[i][i])
print(wed4)
np.diagonal(wed)

2
2
2
2
2
2
2
2
2
2
2
2
[[Timestamp('2019-06-05 00:00:00', freq='D')
  Timestamp('2019-06-12 00:00:00', freq='D')
  Timestamp('2019-06-19 00:00:00', freq='D')
  Timestamp('2019-06-26 00:00:00', freq='D')]
 [Timestamp('2019-07-03 00:00:00', freq='D')
  Timestamp('2019-07-10 00:00:00', freq='D')
  Timestamp('2019-07-17 00:00:00', freq='D')
  Timestamp('2019-07-24 00:00:00', freq='D')]
 [Timestamp('2019-07-31 00:00:00', freq='D')
  Timestamp('2019-08-07 00:00:00', freq='D')
  Timestamp('2019-08-14 00:00:00', freq='D')
  Timestamp('2019-08-21 00:00:00', freq='D')]]
[array([Timestamp('2019-06-12 00:00:00', freq='D'),
       Timestamp('2019-07-10 00:00:00', freq='D'),
       Timestamp('2019-08-07 00:00:00', freq='D')], dtype=object), array([Timestamp('2019-06-26 00:00:00', freq='D'),
       Timestamp('2019-07-24 00:00:00', freq='D'),
       Timestamp('2019-08-21 00:00:00', freq='D')], dtype=object)]
[Timestamp('2019-06-12 00:00:00', freq='D'), Timestamp('2019-06-26 00:00:00', freq='D')]
[Tim

array([Timestamp('2019-06-05 00:00:00', freq='D'),
       Timestamp('2019-07-10 00:00:00', freq='D'),
       Timestamp('2019-08-14 00:00:00', freq='D')], dtype=object)

In [18]:
import numpy as np
num = np.array([5,2,1,1,13,np.nan,4,3,1,4,3,1,2,np.nan,np.nan,1,1,2])
a=np.where(num==1)[0][-1]
print(a)
b=np.count_nonzero(np.isnan(num))
print(b)
num2 = np.delete(num,np.where(np.isnan(num)))
print(num2)
num3 = []
for i in range(0,len(num)):
    num3.append(num[i]**(1/2))
print(num3)

16
3
[ 5.  2.  1.  1. 13.  4.  3.  1.  4.  3.  1.  2.  1.  1.  2.]
[2.23606797749979, 1.4142135623730951, 1.0, 1.0, 3.605551275463989, nan, 2.0, 1.7320508075688772, 1.0, 2.0, 1.7320508075688772, 1.0, 1.4142135623730951, nan, nan, 1.0, 1.0, 1.4142135623730951]


In [1]:
import numpy as np
print("-------5a-------")

arr = np.empty((5,3))
for i in range(5):
    arr[i] = i
print (arr)
print("---------------")
print(arr[[1,3,4]])
print("---------------")
print(arr[[-1,-3]])
print("-------5b--------")
import random
a = np.random.randint(1,24,size=(2,3,4))
print(a.T)
print("-----------------")
print(a.transpose(1,2,0))
print("-------5c--------")
Q5c = np.load('Lab5.5c.npy')
np.flip(Q5c)
Q5d = np.random.randn(24)
np.save('Q5d',Q5d)

-------5a-------
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
---------------
[[1. 1. 1.]
 [3. 3. 3.]
 [4. 4. 4.]]
---------------
[[4. 4. 4.]
 [2. 2. 2.]]
-------5b--------
[[[ 6  2]
  [23 23]
  [ 4  7]]

 [[18  8]
  [20 14]
  [14 21]]

 [[ 7 12]
  [21  1]
  [ 8 20]]

 [[16  6]
  [ 2 11]
  [15  7]]]
-----------------
[[[ 6  2]
  [18  8]
  [ 7 12]
  [16  6]]

 [[23 23]
  [20 14]
  [21  1]
  [ 2 11]]

 [[ 4  7]
  [14 21]
  [ 8 20]
  [15  7]]]
-------5c--------


In [4]:
print("-------------------------------Q6--------")
import numpy as np
Q6 = ['w','x','y','z']
Q6a = np.array([[1,2,3,-2],[3,2,1,2],[2,-1,-2,-3],[2,-3,2,1]])
ans = np.array([6,4,2,8])
ainv = np.linalg.inv(Q6a)
print(np.linalg.solve(Q6a,ans))

-------------------------------Q6--------
[ 1.56944444 -0.69444444  1.625      -0.47222222]


In [ ]:
print("---------------Q7-----------------")
print("---------------Q7a----------------")
import numpy as np
r1 = np.random.randint(0,9,size=(1,10))
r2 = np.random.randint(0,9,size=(1,10))
print("---------------Q7b----------------")
def maxx(r1,r2):
    return max(r1,r2)
print(maxx(3,6))
print("---------------Q7c,d----------------")
def pair_max(arr,arr2):
    arr3 = np.array
    for i in range(0,len(arr[0])):
        arr3 = np.append(arr3,max(arr[0][i],arr2[0][i]))
        return arr3
print(pair_max(r1,r2))

In [ ]:
import numpy as np
print("---------------Q8a----------------")
iris = np.load("iris2d.npy")
print(iris)
print("---------------Q8b----------------")
iris2 = iris[:25,:4 ]
iris2 = iris2.reshape(1,100)
print(iris2)
col = []
row = []
nan = np.random.randint(1,100)
col = np.append(col,(np.random.randint(1,100,nan)))
row = np.append(row,(np.random.randint(1,100,nan)))
for i in np.random.randint(0,len(iris2),np.random.randint(0, len(iris2))):
    iris2[i] = np.nan
countNAN = sum(np.isnan(iris2))
iris2[np.isnan(iris2)] = 999