In [15]:
import numpy
numpy.version.version
arr=numpy.arange(0,100+1)
print(arr)
print("---------------------------------------------------------")
arr1 = [num for num in arr if num % 2 == 0]
print(arr1)
print("---------------------------------------------------------")
arr2 = [num for num in arr if num % 5 == 0]
print(arr2)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
---------------------------------------------------------
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
---------------------------------------------------------
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [16]:
import numpy as np
np.array([0])
print("---------------------------------------------------------")
arr2 =np.arange(51,69)
print(arr2)
print("---------------------------------------------------------")
arr3=arr2.reshape((3,6))
print(arr3)
print("---------------------------------------------------------")
arr4 = arr3.reshape((6,3))
print(arr4)
print("---------------------------------------------------------")

---------------------------------------------------------
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68]
---------------------------------------------------------
[[51 52 53 54 55 56]
 [57 58 59 60 61 62]
 [63 64 65 66 67 68]]
---------------------------------------------------------
[[51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]]
---------------------------------------------------------


In [17]:
import pandas as pd
import numpy as np

data = pd.date_range(start='06/04/2019', end='08/21/2019')
datasave = []
for i in range(1, len(data)):
    if data[i].weekday() == 2:
        print(data[i].weekday())
        datasave.append(data[i])
ans = datasave
wed = np.array(ans)
wed = wed.reshape(3,4)
print(wed)
wed2 = [wed.T[i] for i in range (len(wed.T)) if i %2 !=0]
print(wed2)
wed3 = []
wed3.append(wed[0][1])
wed3.append(wed[0][3])
print(wed3)
wed4 = []
for i in range(0,len(wed)):
    wed4.append(wed[i][i])
print(wed4)
np.diagonal(wed)

2
2
2
2
2
2
2
2
2
2
2
2
[[Timestamp('2019-06-05 00:00:00', freq='D')
  Timestamp('2019-06-12 00:00:00', freq='D')
  Timestamp('2019-06-19 00:00:00', freq='D')
  Timestamp('2019-06-26 00:00:00', freq='D')]
 [Timestamp('2019-07-03 00:00:00', freq='D')
  Timestamp('2019-07-10 00:00:00', freq='D')
  Timestamp('2019-07-17 00:00:00', freq='D')
  Timestamp('2019-07-24 00:00:00', freq='D')]
 [Timestamp('2019-07-31 00:00:00', freq='D')
  Timestamp('2019-08-07 00:00:00', freq='D')
  Timestamp('2019-08-14 00:00:00', freq='D')
  Timestamp('2019-08-21 00:00:00', freq='D')]]
[array([Timestamp('2019-06-12 00:00:00', freq='D'),
       Timestamp('2019-07-10 00:00:00', freq='D'),
       Timestamp('2019-08-07 00:00:00', freq='D')], dtype=object), array([Timestamp('2019-06-26 00:00:00', freq='D'),
       Timestamp('2019-07-24 00:00:00', freq='D'),
       Timestamp('2019-08-21 00:00:00', freq='D')], dtype=object)]
[Timestamp('2019-06-12 00:00:00', freq='D'), Timestamp('2019-06-26 00:00:00', freq='D')]
[Tim

array([Timestamp('2019-06-05 00:00:00', freq='D'),
       Timestamp('2019-07-10 00:00:00', freq='D'),
       Timestamp('2019-08-14 00:00:00', freq='D')], dtype=object)

In [18]:
import numpy as np
num = np.array([5,2,1,1,13,np.nan,4,3,1,4,3,1,2,np.nan,np.nan,1,1,2])
a=np.where(num==1)[0][-1]
print(a)
b=np.count_nonzero(np.isnan(num))
print(b)
num2 = np.delete(num,np.where(np.isnan(num)))
print(num2)
num3 = []
for i in range(0,len(num)):
    num3.append(num[i]**(1/2))
print(num3)

16
3
[ 5.  2.  1.  1. 13.  4.  3.  1.  4.  3.  1.  2.  1.  1.  2.]
[2.23606797749979, 1.4142135623730951, 1.0, 1.0, 3.605551275463989, nan, 2.0, 1.7320508075688772, 1.0, 2.0, 1.7320508075688772, 1.0, 1.4142135623730951, nan, nan, 1.0, 1.0, 1.4142135623730951]
